name: erni
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  riverpod: ^2.2.0
  flutter_riverpod: ^2.2.0
  google_fonts: ^4.0.3
  json_annotation: ^4.8.0
  freezed_annotation: ^2.2.0
  riverpod_annotation: ^1.2.1
  retrofit: ^4.0.1
  dio: ^5.0.0
  auto_route: ^5.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  build_runner: ^2.3.3
  json_serializable: ^6.6.1
  freezed: ^2.3.2
  riverpod_generator: ^1.2.0
  retrofit_generator: ^5.0.0
  auto_route_generator: ^5.0.3
  very_good_analysis: ^4.0.0+1

flutter:
  uses-material-design: true

  # assets:
  #   - images/a_dot_burr.jpeg
  #   - images/a_dot_ham.jpeg

  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
